apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2026-06-16T13:22:03Z"
  generation: 46
  name: app
  namespace: argocd
  resourceVersion: "23275"
  uid: 3bcb305d-5579-43cc-b599-2801c4c2fa06
spec:
  destination:
    namespace: app-argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: yaml
    repoURL: https://github.com/mxmchr/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true